[supervisord]
nodaemon=true

[program:familyplanner]
# The command that supervisord will run
command=/home/nt/.local/bin/uwsgi --ini /home/nt/etc/uwsgi/familyplanner.ini

# Automatically restart if the process exits unexpectedly
autorestart=true

# Start automatically when supervisord starts
autostart=true

# Redirect STDOUT and STDERR to log files
stdout_logfile=/home/nt/logs/familyplanner-stdout.log
stderr_logfile=/home/nt/logs/familyplanner-stderr.log

startsecs=5
stopasgroup=true
killasgroup=true
