[supervisord]
nodaemon=true
logfile=%(ENV_HOME)s/logs/supervisord.log
pidfile=%(ENV_HOME)s/run/supervisord.pid

[unix_http_server]
file=%(ENV_HOME)s/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix://%(ENV_HOME)s/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:familyplanner]
command=%(ENV_HOME)s/.local/bin/uwsgi --ini %(ENV_HOME)s/etc/uwsgi/familyplanner.ini
autorestart=true
autostart=true
stdout_logfile=%(ENV_HOME)s/logs/familyplanner-stdout.log
stderr_logfile=%(ENV_HOME)s/logs/familyplanner-stderr.log
startsecs=5
stopasgroup=true
killasgroup=true
